Mejora en pasarela de pagos
edgartellom/Henry-Final-Project pull request #29
Opened 2023-04-13 16:19 UTC by GonzaloLeguiza

Ya esta funcionando el boton del carrito para pagar,tambien redirecciona bien una vez hecho o no el pago.
Como modificacion cambie la ubicacion del Failure y Success a la carpeta Pages porque se renderizan de manera independiente en una ruta específica,tambien agrege algo de estilo para que quede aceptable.

2023-04-15 22:45 UTC, edgartellom requested changes
Revisar los cambios sugeridos para poder subir los cambios a producción. Las observaciones son en términos generales referidos a un correcto ruteo o redireccionamiento.

2023-04-15 22:45 UTC, edgartellom commented on api/src/controllers/mercadopagoController.js
>    const preference = {
Esto puede traer conflicto con la versión deployada porque le estas pasando una URL local, trata de manejar una lógica para pasarle una URL valida tanto de manera local como en la deployada

2023-04-15 22:45 UTC, edgartellom commented on client/src/pages/paymentState/Success.jsx
> +const Success = () => {
Lo mismo acá cuidado con usar el ruteo adecuado

2023-04-15 22:45 UTC, edgartellom commented on client/src/pages/shoppingCart/Cart.jsx
> +
Acá no es necesario poner localhost:3001. Está configurado para que axios tome la URL ya sea local o deployada por default

2023-04-15 22:45 UTC, edgartellom commented on client/src/pages/paymentState/Failure.jsx
> +    const timer = setTimeout(() => {
Modificar el ruteo, puedes usar navigate de react-router-dom (si es a home la url seria unicamente ("/"), si es a products seria ("/products")

2023-04-15 22:47 UTC, edgartellom requested changes

2023-04-15 22:47 UTC, edgartellom commented on api/src/controllers/mercadopagoController.js
> +        success: 'http://127.0.0.1:5173/success', // URL de retorno en caso de éxito
Esto puede traer conflicto con la versión deployada porque le estas pasando una URL local, trata de manejar una lógica para pasarle una URL valida tanto de manera local como en la deployada

2023-04-15 22:47 UTC, edgartellom commented on client/src/pages/paymentState/Failure.jsx
> +      window.location.href = 'http://127.0.0.1:5173/';
Modificar el ruteo, puedes usar navigate de react-router-dom (si es a home la url seria unicamente ("/"), si es a products seria ("/products")

2023-04-15 22:50 UTC, edgartellom requested changes

2023-04-15 22:50 UTC, edgartellom commented on client/src/pages/paymentState/Success.jsx
> +      window.location.href = 'http://127.0.0.1:5173/';
Lo mismo acá cuidado con usar el ruteo adecuado

2023-04-15 22:50 UTC, edgartellom commented on client/src/pages/shoppingCart/Cart.jsx
> +    axios.post('http://localhost:3001/mercadopago/create-payment', data)
Acá no es necesario poner localhost:3001. Está configurado para que axios tome la URL ya sea local o deployada por default

2023-04-18 00:43 UTC, edgartellom approved these changes
Ok!

2023-04-18 00:44 UTC, diegobonzo approved these changes
ok

2023-04-18 00:44 UTC, merged