Create
edgartellom/Henry-Final-Project pull request #9
Opened 2023-03-23 23:11 UTC by ktorresmath

2023-03-24 15:37 UTC, edgartellom requested changes
No debes crear una carpeta zustand dentro de componentes para desarrollar la lógica de estados.
En vez de ello, debes crear un archivo "categories.js" por ejemplo dentro de la carpeta store.

2023-03-25 21:37 UTC, edgartellom approved these changes
Ok. Si no es necesario los comentarios mejor quitarlos

2023-03-27 23:36 UTC, Rolas444 approved these changes
ok

2023-03-27 23:38 UTC, Rolas444 commented
ok

2023-03-27 23:39 UTC, merged